# Generated by Django 4.1.7 on 2023-05-17 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="Product_status",),
        migrations.AlterField(
            model_name="bootstrap",
            name="is_best",
            field=models.BooleanField(default=False, verbose_name="Лучшие товары"),
        ),
        migrations.AlterField(
            model_name="bootstrap",
            name="is_new",
            field=models.BooleanField(default=False, verbose_name="Новинки"),
        ),
    ]
