# Generated by Django 4.1.7 on 2023-07-07 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='under_category',
            new_name='category',
        ),
    ]
