# Generated by Django 4.1.7 on 2023-07-07 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_under_category_products_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='level',
            new_name='mptt_level',
        ),
    ]
